adi_test:
    resource: "@AdiTestBundle/Controller/"
    type:     annotation
    prefix:   /adi

#---^^^---------- CUSTOM USER BUNDLES -------------^^^---#
#---NOTE: All bundles in this file are prefixed (/app)---#
#---NOTE: Check in routing_platform.yml -----------------#