security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
            ROLE_ADMIN:       [ROLE_USER, ROLE_MANAGER]
            ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    providers:
            fos_userbundle:
                id: fos_user.user_provider.username_email

    firewalls:
        dev:
                pattern: ^/(_(profiler|wdt)|css|images|js)/
                security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /security/login
                check_path: /security/login_check
            logout:
                path: /security/logout
                target: /
            anonymous: true

    access_control:
            - { path: ^/security/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/, role: ROLE_USER }
            - { path: ^/admin, role: ROLE_ADMIN }

